package ResourceDiscovery;

public enum AssetType {
    INSTANCE_COMPUTE_ASSET,
    DISK_COMPUTE_ASSET,
    TOPIC_PUB_SUB_ASSET,
    SUBSCRIPTION_PUB_SUB_ASSET,
    BUCKET_STORAGE_ASSET,
    INSTANCE_CLOUD_SQL_ASSET
}

